import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck, Clock, ArrowRight, CheckCircle, CheckSquare, Circle, AlertTriangle, Loader2, Menu, X, Grid } from 'lucide-react';
import { Exam, StudentSession, UserRole, QuestionType } from '../../types';
import { useApp } from '../../contexts/AppContext';
import { api } from '../../services/api';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { Badge } from '../ui/Badge';
import { TextArea } from '../ui/TextArea';
import { RichTextEditor } from '../ui/RichTextEditor';

export const ActiveExam = () => {
  const { auth, logViolation, submitExamSession, startExamSession, logout } = useApp();
  const navigate = useNavigate();
  const videoRef = useRef<HTMLVideoElement>(null);
  
  // --- Local State ---
  const [initStatus, setInitStatus] = useState<'LOADING' | 'READY' | 'SUBMITTING' | 'ERROR'>('LOADING');
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, any>>({});
  const answersRef = useRef<Record<string, any>>({}); // Ref to track latest answers for async access
  const [timeLeft, setTimeLeft] = useState<number | null>(null); // Remaining seconds
  const [activeExamData, setActiveExamData] = useState<{ exam: Exam, session: StudentSession } | null>(null);
  const [isNavOpen, setIsNavOpen] = useState(false);

  // --- 1. Initialization Logic ---
  useEffect(() => {
    const initializeExam = async () => {
      try {
        // Verify User
        if (!auth.user || auth.user.role !== UserRole.STUDENT) {
          navigate('/');
          return;
        }

        // DIRECT FETCH to avoid stale context race conditions
        const data = await api.data.fetchAll();
        
        // Find relevant session from FRESH data
        const userSessions = data.sessions.filter(s => s.studentId === auth.user?.id);
        const activeSession = userSessions.find(s => s.status === 'IN_PROGRESS') || userSessions.find(s => s.status === 'WAITING');
        const completedSession = userSessions.find(s => s.status === 'SUBMITTED' || s.status === 'COMPLETED');

        if (completedSession && !activeSession) {
           navigate('/student/completed');
           return;
        }

        if (!activeSession) {
           console.error("No active session found for user", auth.user.id);
           setInitStatus('ERROR');
           return;
        }

        const exam = data.exams.find(e => e.id === activeSession.examId);
        if (!exam) {
          console.error("Exam not found for session", activeSession.examId);
          setInitStatus('ERROR');
          return;
        }

        // Start Session if needed (Idempotent call)
        let freshSession = activeSession;
        if (activeSession.status === 'WAITING') {
           await startExamSession(auth.user.id, exam.id);
           // Fetch one more time to get the start time generated by backend
           const refreshedData = await api.data.fetchAll();
           freshSession = refreshedData.sessions.find(s => s.studentId === auth.user?.id && s.examId === exam.id)!;
        }

        if (!freshSession || !freshSession.startTime) {
           console.error("Session failed to initialize start time");
           setInitStatus('ERROR'); 
           return;
        }

        // Calculate Time Left relative to Start Time
        const now = Date.now();
        const elapsedSeconds = Math.floor((now - freshSession.startTime) / 1000);
        const totalSeconds = exam.durationMinutes * 60;
        const remaining = totalSeconds - elapsedSeconds;

        if (remaining <= 0) {
           // Expired on load
           handleSubmit(freshSession.studentId, exam.id, {}, true); // Pass true to skip state updates if component unmounting
           return;
        }

        // Set State
        setTimeLeft(remaining);
        setActiveExamData({ exam, session: freshSession });
        setAnswers(freshSession.answers || {});
        answersRef.current = freshSession.answers || {}; // Init ref
        setInitStatus('READY');

      } catch (e) {
        console.error(e);
        setInitStatus('ERROR');
      }
    };

    // Only run on mount or if status is LOADING
    if (initStatus === 'LOADING') {
      initializeExam();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- 2. Timer Logic ---
  useEffect(() => {
    if (initStatus !== 'READY' || timeLeft === null) return;

    if (timeLeft <= 0) {
      // Time is up!
      if (activeExamData) {
        handleSubmit(activeExamData.session.studentId, activeExamData.exam.id, answers);
      }
      return;
    }

    const timerId = setInterval(() => {
      setTimeLeft(prev => {
        if (prev === null) return null;
        if (prev <= 1) {
          clearInterval(timerId);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timerId);
  }, [initStatus, timeLeft]);

  // --- 3. Security: Fullscreen & Tab Switch ---
  useEffect(() => {
    if (initStatus !== 'READY') return;

    const handleVisibility = () => {
      if (document.hidden && auth.user) {
        console.log('🚨 TAB SWITCH DETECTED - Logging violation');
        logViolation(auth.user.id, { timestamp: Date.now(), type: 'TAB_SWITCH' });
        alert("WARNING: Tab switching is monitored and has been recorded.");
      }
    };

    const handleFullscreenChange = () => {
      if (!document.fullscreenElement && auth.user) {
        console.log('🚨 FULLSCREEN EXIT DETECTED - Logging violation');
        logViolation(auth.user.id, { timestamp: Date.now(), type: 'FULLSCREEN_EXIT' });
        alert("WARNING: Exiting fullscreen is monitored and has been recorded.");
      }
    };

    const enforceFullscreen = async () => {
      try {
        if (!document.fullscreenElement && document.documentElement.requestFullscreen) {
           await document.documentElement.requestFullscreen();
        }
      } catch (e) { /* ignore */ }
    };

    document.addEventListener("visibilitychange", handleVisibility);
    document.addEventListener("fullscreenchange", handleFullscreenChange);
    window.addEventListener("click", enforceFullscreen); // Retry FS on interaction

    return () => {
      document.removeEventListener("visibilitychange", handleVisibility);
      document.removeEventListener("fullscreenchange", handleFullscreenChange);
      window.removeEventListener("click", enforceFullscreen);
    };
  }, [initStatus]);

  // --- 4. Webcam ---
  useEffect(() => {
    if (initStatus !== 'READY') return;
    
    const startCam = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        if (videoRef.current) videoRef.current.srcObject = stream;
      } catch (e) {
        console.error("Camera denied");
      }
    };
    startCam();
    
    // Frame Streaming
    const streamInterval = setInterval(async () => {
      if (videoRef.current && activeExamData) {
        const canvas = document.createElement('canvas');
        canvas.width = 320;
        canvas.height = 240;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
          const frameData = canvas.toDataURL('image/jpeg', 0.5);
          try {
             await api.sessions.updateFrame(activeExamData.session.studentId, activeExamData.exam.id, frameData);
          } catch (e) {
             // Silent fail
          }
        }
      }
    }, 5000);

    // Cleanup tracks
    return () => {
      clearInterval(streamInterval);
      if (videoRef.current && videoRef.current.srcObject) {
        const stream = videoRef.current.srcObject as MediaStream;
        stream.getTracks().forEach(t => t.stop());
      }
    };
  }, [initStatus, activeExamData]);

  // --- 5. Warnings Listener ---
  useEffect(() => {
    if (initStatus !== 'READY' || !activeExamData) return;

    // Poll for warnings every 5 seconds
    const warningInterval = setInterval(async () => {
      try {
        // Construct proper session ID
        const sessionId = `${activeExamData.session.studentId}_${activeExamData.exam.id}`;
        
        // Fetch the latest session data
        const data = await api.data.fetchAll();
        const currentSession = data.sessions.find(s => 
          s.studentId === activeExamData.session.studentId && 
          s.examId === activeExamData.exam.id
        );
        
        if (currentSession) {
           // Check for Termination / Status Change
           if (currentSession.status === 'SUBMITTED' || currentSession.status === 'COMPLETED') {
              // If the session was terminated externally (by proctor) and we haven't submitted locally yet,
              // we MUST save the current answers before leaving.
              if (activeExamData.session.status !== 'SUBMITTED' && activeExamData.session.status !== 'COMPLETED') {
                  console.log("⚠️ Session terminated externally. Saving final answers...");
                  try {
                    // Use the REF to get the latest answers since state might be stale in this closure
                    await api.sessions.submit(activeExamData.session.studentId, activeExamData.exam.id, answersRef.current);
                  } catch (err) {
                    console.error("Failed to save final answers on termination:", err);
                  }
              }

              alert("Session Ended: Your exam has been submitted or terminated by the proctor.");
              navigate('/student/completed');
              return;
           }

           // Check for Warnings
           if (currentSession.warnings && currentSession.warnings.length > (activeExamData.session.warnings?.length || 0)) {
              // New warning found!
              const newWarnings = currentSession.warnings.slice(activeExamData.session.warnings?.length || 0);
              newWarnings.forEach(w => alert(`⚠️ PROCTOR WARNING: ${w}`));
              
              // Update local state to avoid re-alerting
              setActiveExamData(prev => prev ? ({...prev, session: currentSession}) : null);
           }
        }
      } catch (e) {
        // silent fail
      }
    }, 5000);

    return () => clearInterval(warningInterval);
  }, [initStatus, activeExamData]);


  // --- Handlers ---
  const handleAnswer = (val: any) => {
    if (!activeExamData) return;
    const qId = activeExamData.exam.questions[currentQuestionIndex].id;
    const qType = activeExamData.exam.questions[currentQuestionIndex].type;

    if (qType === QuestionType.MULTI_SELECT) {
       const current = (answers[qId] as string[]) || [];
       let newVal;
       if (current.includes(val)) {
         newVal = current.filter(v => v !== val);
       } else {
         newVal = [...current, val];
       }
       setAnswers(prev => {
         const newAnswers = {...prev, [qId]: newVal};
         answersRef.current = newAnswers; // Sync ref
         return newAnswers;
       });
    } else {
       setAnswers(prev => {
         const newAnswers = {...prev, [qId]: val};
         answersRef.current = newAnswers; // Sync ref
         return newAnswers;
       });
    }
  };

  const handleSubmit = async (stuId = activeExamData?.session.studentId, exId = activeExamData?.exam.id, finalAnswers = answers, skipState = false) => {
     if (!stuId || !exId) return;
     
     if (!skipState) setInitStatus('SUBMITTING'); 
     
     try {
       await submitExamSession(stuId, exId, finalAnswers);
       if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
       navigate('/student/completed');
     } catch (e) {
       if (!skipState) {
        alert("Submission failed. Please try again.");
        setInitStatus('READY');
       }
     }
  };

  // --- RENDER ---

  if (initStatus === 'LOADING' || initStatus === 'SUBMITTING') {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-950 text-violet-600">
        <Loader2 size={48} className="animate-spin mb-4"/>
        <h2 className="text-xl font-bold text-gray-700 dark:text-gray-300">
          {initStatus === 'LOADING' ? 'Preparing Secure Environment...' : 'Encrypting & Submitting Responses...'}
        </h2>
      </div>
    );
  }

  if (initStatus === 'ERROR' || !activeExamData) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-red-50 dark:bg-red-900/20 text-red-600 p-4 text-center">
         <AlertTriangle size={48} className="mb-4"/>
         <h2 className="text-2xl font-bold mb-2">Session Error</h2>
         <p>Could not load exam session. Please contact your proctor.</p>
         <Button className="mt-6" onClick={() => { logout(); navigate('/'); }}>Return Home</Button>
      </div>
    );
  }

  const { exam } = activeExamData;
  const currentQ = exam.questions[currentQuestionIndex];
  const currentA = answers[currentQ.id];

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-black flex flex-col font-sans select-none">
      {/* Header */}
      <header className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 h-auto md:h-20 px-4 py-3 md:py-0 md:px-8 flex flex-wrap md:flex-nowrap justify-between items-center z-50 gap-4">
         <div className="flex items-center gap-4 flex-1">
            <div className="bg-violet-100 dark:bg-violet-900/30 p-2 rounded-lg hidden md:block">
              <ShieldCheck className="text-violet-600 dark:text-violet-400" size={24} />
            </div>
            <div className="min-w-0">
              <h1 className="font-bold text-gray-900 dark:text-white leading-tight truncate text-sm md:text-base">{exam.title}</h1>
              <p className="text-xs text-gray-500 dark:text-gray-400 font-mono truncate">ID: {exam.id}</p>
            </div>
         </div>

         <div className="flex items-center gap-3 md:gap-6">
            <div className={`flex items-center gap-2 md:gap-3 px-3 py-1.5 md:px-4 md:py-2 rounded-full border ${
              (timeLeft || 0) < 300 ? 'bg-red-50 border-red-200 text-red-600 animate-pulse' : 'bg-gray-50 border-gray-200 text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-300'
            }`}>
               <Clock size={16} className="md:w-[18px] md:h-[18px]" />
               <span className="font-mono font-bold text-sm md:text-lg">
                 {Math.floor((timeLeft || 0) / 60)}:{(timeLeft || 0) % 60 < 10 ? '0' : ''}{(timeLeft || 0) % 60}
               </span>
            </div>
            
            <div className="w-20 h-16 md:w-32 md:h-24 bg-black rounded-lg overflow-hidden border-2 border-gray-800 relative shadow-lg shrink-0">
               <video ref={videoRef} autoPlay muted playsInline className="w-full h-full object-cover opacity-80" />
               <div className="absolute top-1 right-1 md:top-2 md:right-2 w-1.5 h-1.5 md:w-2 md:h-2 bg-red-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(239,68,68,0.8)]" />
            </div>

            <button 
              onClick={() => setIsNavOpen(true)}
              className="md:hidden p-2 text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg"
            >
              <Grid size={24} />
            </button>
         </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 container mx-auto max-w-5xl p-4 md:p-6 flex flex-col lg:flex-row gap-6 md:gap-8 relative">
         {/* Question Area */}
         <div className="flex-1 space-y-6">
            <Card className="min-h-[400px] flex flex-col">
               <div className="flex justify-between items-start mb-6">
                  <Badge variant="outline">Question {currentQuestionIndex + 1} of {exam.questions.length}</Badge>
                  <span className="text-sm text-gray-500 font-medium">{currentQ.points} Points</span>
               </div>

               <h2 className="text-lg md:text-xl font-medium text-gray-900 dark:text-white mb-8 leading-relaxed">
                 {currentQ.text}
               </h2>

               <div className="flex-1 space-y-4">
                  {currentQ.type === QuestionType.MCQ && currentQ.options?.map((opt, idx) => (
                    <div 
                      key={idx}
                      onClick={() => handleAnswer(opt)}
                      className={`p-4 rounded-xl border-2 cursor-pointer transition-all flex items-center gap-4 ${
                        currentA === opt 
                          ? 'border-violet-600 bg-violet-50 dark:bg-violet-900/20 dark:border-violet-500' 
                          : 'border-gray-200 dark:border-gray-700 hover:border-violet-300 dark:hover:border-violet-700'
                      }`}
                    >
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        currentA === opt ? 'border-violet-600 bg-violet-600 text-white' : 'border-gray-300 dark:border-gray-600'
                      }`}>
                        {currentA === opt && <div className="w-2 h-2 bg-white rounded-full" />}
                      </div>
                      <span className="text-gray-700 dark:text-gray-200 text-sm md:text-base">{opt}</span>
                    </div>
                  ))}

                  {currentQ.type === QuestionType.MULTI_SELECT && currentQ.options?.map((opt, idx) => {
                    const isSelected = (currentA as string[])?.includes(opt);
                    return (
                      <div 
                        key={idx}
                        onClick={() => handleAnswer(opt)}
                        className={`p-4 rounded-xl border-2 cursor-pointer transition-all flex items-center gap-4 ${
                          isSelected
                            ? 'border-violet-600 bg-violet-50 dark:bg-violet-900/20 dark:border-violet-500' 
                            : 'border-gray-200 dark:border-gray-700 hover:border-violet-300 dark:hover:border-violet-700'
                        }`}
                      >
                        <div className={`w-6 h-6 rounded border-2 flex items-center justify-center shrink-0 ${
                          isSelected ? 'border-violet-600 bg-violet-600 text-white' : 'border-gray-300 dark:border-gray-600'
                        }`}>
                          {isSelected && <CheckSquare size={14} />}
                        </div>
                        <span className="text-gray-700 dark:text-gray-200 text-sm md:text-base">{opt}</span>
                      </div>
                    );
                  })}

                  {currentQ.type === QuestionType.TRUE_FALSE && ['True', 'False'].map((opt) => (
                    <div 
                      key={opt}
                      onClick={() => handleAnswer(opt)}
                      className={`p-4 rounded-xl border-2 cursor-pointer transition-all flex items-center gap-4 ${
                        currentA === opt 
                          ? 'border-violet-600 bg-violet-50 dark:bg-violet-900/20 dark:border-violet-500' 
                          : 'border-gray-200 dark:border-gray-700 hover:border-violet-300 dark:hover:border-violet-700'
                      }`}
                    >
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        currentA === opt ? 'border-violet-600 bg-violet-600 text-white' : 'border-gray-300 dark:border-gray-600'
                      }`}>
                        {currentA === opt && <div className="w-2 h-2 bg-white rounded-full" />}
                      </div>
                      <span className="text-gray-700 dark:text-gray-200 text-sm md:text-base">{opt}</span>
                    </div>
                  ))}

                  {(currentQ.type === QuestionType.SHORT_ANSWER || currentQ.type === QuestionType.ESSAY) && (
                    <RichTextEditor 
                      key={currentQ.id}
                      placeholder="Type your answer here..."
                      value={currentA || ''}
                      onChange={(val) => handleAnswer(val)}
                      className="min-h-[300px]"
                    />
                  )}
               </div>
            </Card>

            <div className="flex justify-between items-center pb-20 md:pb-0">
               <Button 
                 variant="ghost" 
                 disabled={currentQuestionIndex === 0}
                 onClick={() => setCurrentQuestionIndex(prev => prev - 1)}
               >
                 Previous
               </Button>
               
               {currentQuestionIndex < exam.questions.length - 1 ? (
                 <Button 
                   onClick={() => setCurrentQuestionIndex(prev => prev + 1)}
                   className="gap-2"
                 >
                   Next Question <ArrowRight size={18} />
                 </Button>
               ) : (
                 <Button 
                   variant="primary"
                   className="bg-emerald-600 hover:bg-emerald-700 text-white gap-2 px-8"
                   onClick={() => handleSubmit()}
                 >
                   Submit Exam <CheckCircle size={18} />
                 </Button>
               )}
            </div>
         </div>

         {/* Sidebar Navigation - Responsive Drawer */}
         <>
           {/* Overlay */}
           {isNavOpen && (
             <div 
               className="fixed inset-0 bg-black/50 z-40 lg:hidden backdrop-blur-sm"
               onClick={() => setIsNavOpen(false)}
             />
           )}
           
           <div className={`
             fixed lg:sticky lg:self-start top-0 lg:top-4 right-0 h-screen lg:h-auto w-72 lg:w-64 bg-white dark:bg-gray-900 lg:bg-transparent lg:dark:bg-transparent z-50 lg:z-0 p-6 lg:p-0 shadow-2xl lg:shadow-none transition-transform duration-300 ease-in-out overflow-y-auto
             ${isNavOpen ? 'translate-x-0' : 'translate-x-full lg:translate-x-0'}
           `}>
              <div className="flex justify-between items-center mb-6 lg:hidden">
                <h3 className="font-bold text-lg">Question Map</h3>
                <button onClick={() => setIsNavOpen(false)}><X size={24}/></button>
              </div>

              <div className="space-y-6">
                <Card className="p-4">
                   <h3 className="font-bold text-gray-900 dark:text-white mb-4 text-sm uppercase tracking-wider hidden lg:block">Question Navigator</h3>
                   <div className="grid grid-cols-4 gap-2">
                      {exam.questions.map((q, idx) => {
                        const isAnswered = answers[q.id] !== undefined && answers[q.id] !== '' && (Array.isArray(answers[q.id]) ? answers[q.id].length > 0 : true);
                        const isCurrent = idx === currentQuestionIndex;
                        
                        return (
                          <button
                            key={q.id}
                            onClick={() => {
                              setCurrentQuestionIndex(idx);
                              setIsNavOpen(false);
                            }}
                            className={`aspect-square rounded-lg flex items-center justify-center text-sm font-bold transition-all ${
                              isCurrent 
                                ? 'bg-violet-600 text-white ring-2 ring-violet-300 dark:ring-violet-800' 
                                : isAnswered
                                  ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
                                  : 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700'
                            }`}
                          >
                            {idx + 1}
                          </button>
                        );
                      })}
                   </div>
                </Card>
                
                <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl border border-blue-100 dark:border-blue-800">
                   <h4 className="font-bold text-blue-800 dark:text-blue-300 text-sm mb-2 flex items-center gap-2">
                     <ShieldCheck size={16}/> Proctor Active
                   </h4>
                   <p className="text-xs text-blue-600 dark:text-blue-400 leading-relaxed">
                     Your session is being monitored. Please keep your face visible and do not switch tabs.
                   </p>
                </div>
              </div>
           </div>
         </>
      </main>
    </div>
  );
};
